create database ecommerce;
use ecommerce;

/*Display all columns from the orders table.*/

select * from orders;

/*Display all columns from the products table.*/

select * from products;

/*Show only order_id, product_id, and quantity from orders.*/

select  OrderID, ProductId, Quantity from orders;

/*Show all products that belong to a specific category (pick any one category).*/

select * from products where Category = 'Fashion';

/*Find all orders where the quantity is greater than 3.*/

select * from orders where Quantity > 3;

/*Display products whose price is greater than 500.*/

select Product, Price from products where Price > 500;

/*Show all orders where the quantity is greater than the average quantity of all orders.*/

select OrderID, Quantity from Orders where Quantity > (select avg(Quantity) from Orders);

/*Display products sorted by price in descending order.*/

select Product, Price from products order by Price desc;

/*Show the top 5 most expensive products.*/

select Product, Price from products order by price desc limit 5;

/*Find orders where quantity is between 2 and 5.*/

select OrderID, Quantity from orders where quantity between 2 and 5;

/*Display products whose name contains a specific word (use LIKE).*/

select Product from products where Product like 'S%';

/*Count the total number of orders.*/

select count(Quantity) from Orders;

/*Find the total quantity ordered across all orders.*/

select sum(Quantity) from Orders;

/*Find the average price of all products.*/

select avg(Price) from Products;

/*Find the minimum and maximum product price.*/

select min(Price) as 'minimum price', max(Price) as 'maximum price' from products;

/*Count how many products exist in each category.*/

select count(Product), Category from products group by Category;

/*Find total quantity ordered for each product.*/

select ProductId, sum(Quantity) from orders group by  ProductId;

select p.Product, sum(o.Quantity) from products p join orders o on o.ProductId = p.ProductId group by p.Product;

/*Find total number of orders per product.*/

select ProductId, count(*) from orders group by ProductId;

/*Display products that have been ordered more than 5 times.*/

select p.Product, sum(o.Quantity) from products p join orders o on o.ProductId = p.ProductId group by p.Product having sum(o.Quantity)>5;

/*Find categories where the average product price is greater than 1000.*/

select Category,  avg(Price) from products group by Category having avg(Price)> 1000;

/*Display order details along with product name.*/

select o.OrderID, p.Product from orders o inner join products p on o.ProductId = p.productId;

/*Show order ID, product name, price, and quantity.*/

select o.OrderId, p.Product, p.Price, O.quantity from orders o inner join products p on o.ProductId = p.ProductId;

/*Find total sales value for each order (price × quantity).*/

select o.OrderID, sum(p.Price*o.Quantity) from orders o join products p on o.ProductId = p.ProductId group by o.OrderID;

/*Find total revenue generated by each product.*/

select p.Product, sum(p.Price*o.Quantity) from orders o join products p on o.ProductId= p.ProductId group by p.Product;

/*Find the top 5 best-selling products based on total quantity sold.*/

 select p.product, sum(o.Quantity) from orders o join products p on o.ProductId = p.ProductId  group by p.Product order by sum(o.Quantity)  desc limit 5;
 
/*Find products that have never been ordered.*/

select p.Product, p.ProductId from products p left join orders o on o.ProductId  = p.ProductId where o.ProductId is null;

/*Find the product that generated the highest revenue.*/

select p.Product, sum(p.Price*o.Quantity) as 'Total Revenue' from products p join orders o on o.ProductId = p.ProductId group by p.Product order by sum(p.price*o.quantity) desc limit 1;

/*Find the product that has the highest number of orders.*/

select p.Product, count(o.OrderID) as 'Highest number of orders' from products p join orders o on o.ProductId = p.ProductId group by p.Product order by count(o.OrderID) desc limit 1; 

/*Find the category that generated the most revenue.*/

select p.Category, sum(p.Price* o.Quantity) as 'Revenue' from products p inner join orders o on o.ProductId = p.ProductId group by p.Category order by sum(p.Price*o.Quantity) desc limit 1;

/*Find orders where the total order value is greater than 5000.*/

select o.OrderID, sum(p.Price*o.Quantity) as 'Total order value' from products p join orders o on o.ProductID = p.ProductId group by o.OrderID having sum(p.Price*o.Quantity) > 5000;
